class GameItem {

    txtFileNo := 0
    itemCode := ""
    
    qualityNo := 0
    name := ""
    localizedName := ""
    itemLoc := 0
    quality := ""
    itemx := 0
    itemy := 0 
    numSockets := 0
    identified := false
    ethereal := false

    __new(txtFileNo, qualityNo) {
        this.txtFileNo := txtFileNo
        this.qualityNo := qualityNo
        this.setItemName(txtFileNo)
        this.setQuality(qualityNo)
        this.setLocalizedName(txtFileNo)
    }

    isGem() {
        if ((this.txtFileNo >= 557 and this.txtFileNo <= 586) or (this.txtFileNo >= 597 and this.txtFileNo <= 601)) {
            return true
        }
        return false
    }

    isRune() {
        if (this.txtFileNo >= 629 and this.txtFileNo <= 642) {
            return true
        }
        return false
    }

    getHash() {
        return this.txtFileNo "-" this.itemx "-" this.itemy
    }

    getTextToSpeech() {
        quality := this.getLocalizedQuality(qualityNo)
        if (qualityNo == 2)
            quality := ""
        itemName := this.localizedName
        sockets := ""
        if (this.numSockets > 0) {
            sockets := this.getLocalizedSockets(this.numSockets)
        }
        speechString := quality " " itemName " " sockets
        return speechString
    }

    toString() {
        return "txtFileNo: " this.txtFileNo ", name: " this.name ", itemLoc: " this.itemLoc ", quality: " this.quality ", isRune: " this.isRune() ", id: " this.identified ", eth: " this.ethereal ", itemx: " this.itemx ", itemy: " this.itemy
    }

    calculateFlags(flags) {
        flagsList := []
        SetFormat Integer, H
        hexFlags := flags + 0
        SetFormat Integer, D
        
        ; if (0x00000002 & flags) {  ; IFLAG_TARGET
        ;     ; flagsList.push("IFLAG_TARGET") 
        ; }
        ; if (0x00000004 & flags) {  ; IFLAG_TARGETING
        ;     ; flagsList.push("IFLAG_TARGETING") 
        ; }
        ; if (0x00000008 & flags) {  ; IFLAG_TARGET
        ;     ; flagsList.push("IFLAG_TARGET") 
        ; }
        if (0x00000010 & flags) {  ; IFLAG_IDENTIFIED
            this.identified := true
        }
        ; if (0x00000020 & flags) {  ; IFLAG_QUANTITY
        ;     ; flagsList.push("IFLAG_QUANTITY") 
        ; }
        ; if (0x00000040 & flags) {  ; IFLAG_SWITCHIN
        ;     ; flagsList.push("IFLAG_SWITCHIN") 
        ; }
        ; if (0x00000080 & flags) {  ; IFLAG_SWITCHOUT
        ;     ; flagsList.push("IFLAG_SWITCHOUT") 
        ; }
        ; if (0x00000100 & flags) {  ; IFLAG_BROKEN
        ;     ; flagsList.push("IFLAG_BROKEN") 
        ; }
        ; if (0x00000200 & flags) {  ; IFLAG_REPAIRED
        ;     ; flagsList.push("IFLAG_REPAIRED") 
        ; }
        ; if (0x00000400 & flags) {  ; IFLAG_UNK1
        ;     ; flagsList.push("IFLAG_UNK1") 
        ; }
        ; if (0x00000800 & flags) {  ; IFLAG_SOCKETED
        ;     this.socketed := true
        ;     ; flagsList.push("IFLAG_SOCKETED") 
        ; }
        ; if (0x00001000 & flags) {  ; IFLAG_NOSELL
        ;     ; flagsList.push("IFLAG_NOSELL") 
        ; }
        ; if (0x00002000 & flags) {  ; IFLAG_INSTORE
        ;     ; flagsList.push("IFLAG_INSTORE") 
        ; }
        ; if (0x00004000 & flags) {  ; IFLAG_NOEQUIP
        ;     ; flagsList.push("IFLAG_NOEQUIP") 
        ; }
        ; if (0x00008000 & flags) {  ; IFLAG_NAMED
        ;     ; flagsList.push("IFLAG_NAMED")
        ; } 
        ; if (0x00010000 & flags) {  ; IFLAG_ISEAR
        ;     ; flagsList.push("IFLAG_ISEAR") 
        ; }
        ; ; if (0x00020000 & flags) { ; IFLAG_STARTITEM
        ; ;     flagsList.push("IFLAG_STARTITEM") 
        ; }  
        ; if (0x00080000 & flags)  { ; IFLAG_INIT
        ;     ; flagsList.push("IFLAG_INIT") 
        ; }
        if (0x00400000 & flags) { ; IFLAG_ETHEREAL
            this.ethereal := true 
        }
        ; if (0x01000000 & flags) { ; IFLAG_PERSONALIZED
        ;     ; flagsList.push("IFLAG_PERSONALIZED") 
        ; }
        ; if (0x02000000 & flags) { ; IFLAG_LOWQUALITY
        ;     ; flagsList.push("IFLAG_LOWQUALITY") 
        ; }
        ; if (0x04000000 & flags) { ; IFLAG_RUNEWORD
        ;     this.runeword := true
        ; }
        ; if (0x08000000 & flags) { ; IFLAG_ITEM
        ;     ; flagsList.push("IFLAG_ITEM") 
        ; }

        ; sep := ","
        ; for index,param in flagsList
        ;     str .= sep . param
        ; flagsText := SubStr(str, StrLen(sep)+1)
        ; return flagsText
    }

    setQuality(qualityNo) {
        switch (qualityNo) {
            case 1: this.quality := "Inferior"
            case 2: this.quality := "Normal"
            case 3: this.quality := "Superior"
            case 4: this.quality := "Magic"
            case 5: this.quality := "Set"
            case 6: this.quality := "Rare"
            case 7: this.quality := "Unique"
            case 8: this.quality := "Crafted"
            case 9: this.quality := "Tempered"
            default: this.quality := ""
        }
    }

    getLocalizedQuality(qualityNo) {
        qualityStrName := "quality" . qualityNo
        return localizedStrings[qualityStrName]
    }
    getLocalizedSockets(socketNum) {
        socketStrName := "sockets" . socketNum
        return localizedStrings[socketStrName]
    } 

    setLocalizedName(txtFileNo) {
        switch (txtFileNo) {
            case 0: this.localizedName := localizedStrings["hax"]
            case 1: this.localizedName := localizedStrings["axe"]
            case 2: this.localizedName := localizedStrings["2ax"]
            case 3: this.localizedName := localizedStrings["mpi"]
            case 4: this.localizedName := localizedStrings["wax"]
            case 5: this.localizedName := localizedStrings["lax"]
            case 6: this.localizedName := localizedStrings["bax"]
            case 7: this.localizedName := localizedStrings["btx"]
            case 8: this.localizedName := localizedStrings["gax"]
            case 9: this.localizedName := localizedStrings["gix"]
            case 10: this.localizedName := localizedStrings["wnd"]
            case 11: this.localizedName := localizedStrings["ywn"]
            case 12: this.localizedName := localizedStrings["bwn"]
            case 13: this.localizedName := localizedStrings["gwn"]
            case 14: this.localizedName := localizedStrings["clb"]
            case 15: this.localizedName := localizedStrings["scp"]
            case 16: this.localizedName := localizedStrings["gsc"]
            case 17: this.localizedName := localizedStrings["wsp"]
            case 18: this.localizedName := localizedStrings["spc"]
            case 19: this.localizedName := localizedStrings["mac"]
            case 20: this.localizedName := localizedStrings["mst"]
            case 21: this.localizedName := localizedStrings["fla"]
            case 22: this.localizedName := localizedStrings["whm"]
            case 23: this.localizedName := localizedStrings["mau"]
            case 24: this.localizedName := localizedStrings["gma"]
            case 25: this.localizedName := localizedStrings["ssd"]
            case 26: this.localizedName := localizedStrings["scm"]
            case 27: this.localizedName := localizedStrings["sbr"]
            case 28: this.localizedName := localizedStrings["flc"]
            case 29: this.localizedName := localizedStrings["crs"]
            case 30: this.localizedName := localizedStrings["bsd"]
            case 31: this.localizedName := localizedStrings["lsd"]
            case 32: this.localizedName := localizedStrings["wsd"]
            case 33: this.localizedName := localizedStrings["2hs"]
            case 34: this.localizedName := localizedStrings["clm"]
            case 35: this.localizedName := localizedStrings["gis"]
            case 36: this.localizedName := localizedStrings["bsw"]
            case 37: this.localizedName := localizedStrings["flb"]
            case 38: this.localizedName := localizedStrings["gsd"]
            case 39: this.localizedName := localizedStrings["dgr"]
            case 40: this.localizedName := localizedStrings["dir"]
            case 41: this.localizedName := localizedStrings["kri"]
            case 42: this.localizedName := localizedStrings["bld"]
            case 43: this.localizedName := localizedStrings["tkf"]
            case 44: this.localizedName := localizedStrings["tax"]
            case 45: this.localizedName := localizedStrings["bkf"]
            case 46: this.localizedName := localizedStrings["bal"]
            case 47: this.localizedName := localizedStrings["jav"]
            case 48: this.localizedName := localizedStrings["pil"]
            case 49: this.localizedName := localizedStrings["ssp"]
            case 50: this.localizedName := localizedStrings["glv"]
            case 51: this.localizedName := localizedStrings["tsp"]
            case 52: this.localizedName := localizedStrings["spr"]
            case 53: this.localizedName := localizedStrings["tri"]
            case 54: this.localizedName := localizedStrings["brn"]
            case 55: this.localizedName := localizedStrings["spt"]
            case 56: this.localizedName := localizedStrings["pik"]
            case 57: this.localizedName := localizedStrings["bar"]
            case 58: this.localizedName := localizedStrings["vou"]
            case 59: this.localizedName := localizedStrings["scy"]
            case 60: this.localizedName := localizedStrings["pax"]
            case 61: this.localizedName := localizedStrings["hal"]
            case 62: this.localizedName := localizedStrings["wsc"]
            case 63: this.localizedName := localizedStrings["sst"]
            case 64: this.localizedName := localizedStrings["lst"]
            case 65: this.localizedName := localizedStrings["cst"]
            case 66: this.localizedName := localizedStrings["bst"]
            case 67: this.localizedName := localizedStrings["wst"]
            case 68: this.localizedName := localizedStrings["sbw"]
            case 69: this.localizedName := localizedStrings["hbw"]
            case 70: this.localizedName := localizedStrings["lbw"]
            case 71: this.localizedName := localizedStrings["cbw"]
            case 72: this.localizedName := localizedStrings["sbb"]
            case 73: this.localizedName := localizedStrings["lbb"]
            case 74: this.localizedName := localizedStrings["swb"]
            case 75: this.localizedName := localizedStrings["lwb"]
            case 76: this.localizedName := localizedStrings["lxb"]
            case 77: this.localizedName := localizedStrings["mxb"]
            case 78: this.localizedName := localizedStrings["hxb"]
            case 79: this.localizedName := localizedStrings["rxb"]
            case 80: this.localizedName := localizedStrings["gps"]
            case 81: this.localizedName := localizedStrings["ops"]
            case 82: this.localizedName := localizedStrings["gpm"]
            case 83: this.localizedName := localizedStrings["opm"]
            case 84: this.localizedName := localizedStrings["gpl"]
            case 85: this.localizedName := localizedStrings["opl"]
            case 86: this.localizedName := localizedStrings["d33"]
            case 87: this.localizedName := localizedStrings["g33"]
            case 88: this.localizedName := localizedStrings["leg"]
            case 89: this.localizedName := localizedStrings["hdm"]
            case 90: this.localizedName := localizedStrings["hfh"]
            case 91: this.localizedName := localizedStrings["hst"]
            case 92: this.localizedName := localizedStrings["msf"]
            case 93: this.localizedName := localizedStrings["9ha"]
            case 94: this.localizedName := localizedStrings["9ax"]
            case 95: this.localizedName := localizedStrings["92a"]
            case 96: this.localizedName := localizedStrings["9mp"]
            case 97: this.localizedName := localizedStrings["9wa"]
            case 98: this.localizedName := localizedStrings["9la"]
            case 99: this.localizedName := localizedStrings["9ba"]
            case 100: this.localizedName := localizedStrings["9bt"]
            case 101: this.localizedName := localizedStrings["9ga"]
            case 102: this.localizedName := localizedStrings["9gi"]
            case 103: this.localizedName := localizedStrings["9wn"]
            case 104: this.localizedName := localizedStrings["9yw"]
            case 105: this.localizedName := localizedStrings["9bw"]
            case 106: this.localizedName := localizedStrings["9gw"]
            case 107: this.localizedName := localizedStrings["9cl"]
            case 108: this.localizedName := localizedStrings["9sc"]
            case 109: this.localizedName := localizedStrings["9qs"]
            case 110: this.localizedName := localizedStrings["9ws"]
            case 111: this.localizedName := localizedStrings["9sp"]
            case 112: this.localizedName := localizedStrings["9ma"]
            case 113: this.localizedName := localizedStrings["9mt"]
            case 114: this.localizedName := localizedStrings["9fl"]
            case 115: this.localizedName := localizedStrings["9wh"]
            case 116: this.localizedName := localizedStrings["9m9"]
            case 117: this.localizedName := localizedStrings["9gm"]
            case 118: this.localizedName := localizedStrings["9ss"]
            case 119: this.localizedName := localizedStrings["9sm"]
            case 120: this.localizedName := localizedStrings["9sb"]
            case 121: this.localizedName := localizedStrings["9fc"]
            case 122: this.localizedName := localizedStrings["9cr"]
            case 123: this.localizedName := localizedStrings["9bs"]
            case 124: this.localizedName := localizedStrings["9ls"]
            case 125: this.localizedName := localizedStrings["9wd"]
            case 126: this.localizedName := localizedStrings["92h"]
            case 127: this.localizedName := localizedStrings["9cm"]
            case 128: this.localizedName := localizedStrings["9gs"]
            case 129: this.localizedName := localizedStrings["9b9"]
            case 130: this.localizedName := localizedStrings["9fb"]
            case 131: this.localizedName := localizedStrings["9gd"]
            case 132: this.localizedName := localizedStrings["9dg"]
            case 133: this.localizedName := localizedStrings["9di"]
            case 134: this.localizedName := localizedStrings["9kr"]
            case 135: this.localizedName := localizedStrings["9bl"]
            case 136: this.localizedName := localizedStrings["9tk"]
            case 137: this.localizedName := localizedStrings["9ta"]
            case 138: this.localizedName := localizedStrings["9bk"]
            case 139: this.localizedName := localizedStrings["9b8"]
            case 140: this.localizedName := localizedStrings["9ja"]
            case 141: this.localizedName := localizedStrings["9pi"]
            case 142: this.localizedName := localizedStrings["9s9"]
            case 143: this.localizedName := localizedStrings["9gl"]
            case 144: this.localizedName := localizedStrings["9ts"]
            case 145: this.localizedName := localizedStrings["9sr"]
            case 146: this.localizedName := localizedStrings["9tr"]
            case 147: this.localizedName := localizedStrings["9br"]
            case 148: this.localizedName := localizedStrings["9st"]
            case 149: this.localizedName := localizedStrings["9p9"]
            case 150: this.localizedName := localizedStrings["9b7"]
            case 151: this.localizedName := localizedStrings["9vo"]
            case 152: this.localizedName := localizedStrings["9s8"]
            case 153: this.localizedName := localizedStrings["9pa"]
            case 154: this.localizedName := localizedStrings["9h9"]
            case 155: this.localizedName := localizedStrings["9wc"]
            case 156: this.localizedName := localizedStrings["8ss"]
            case 157: this.localizedName := localizedStrings["8ls"]
            case 158: this.localizedName := localizedStrings["8cs"]
            case 159: this.localizedName := localizedStrings["8bs"]
            case 160: this.localizedName := localizedStrings["8ws"]
            case 161: this.localizedName := localizedStrings["8sb"]
            case 162: this.localizedName := localizedStrings["8hb"]
            case 163: this.localizedName := localizedStrings["8lb"]
            case 164: this.localizedName := localizedStrings["8cb"]
            case 165: this.localizedName := localizedStrings["8s8"]
            case 166: this.localizedName := localizedStrings["8l8"]
            case 167: this.localizedName := localizedStrings["8sw"]
            case 168: this.localizedName := localizedStrings["8lw"]
            case 169: this.localizedName := localizedStrings["8lx"]
            case 170: this.localizedName := localizedStrings["8mx"]
            case 171: this.localizedName := localizedStrings["8hx"]
            case 172: this.localizedName := localizedStrings["8rx"]
            case 173: this.localizedName := localizedStrings["qf1"]
            case 174: this.localizedName := localizedStrings["qf2"]
            case 175: this.localizedName := localizedStrings["ktr"]
            case 176: this.localizedName := localizedStrings["wrb"]
            case 177: this.localizedName := localizedStrings["axf"]
            case 178: this.localizedName := localizedStrings["ces"]
            case 179: this.localizedName := localizedStrings["clw"]
            case 180: this.localizedName := localizedStrings["btl"]
            case 181: this.localizedName := localizedStrings["skr"]
            case 182: this.localizedName := localizedStrings["9ar"]
            case 183: this.localizedName := localizedStrings["9wb"]
            case 184: this.localizedName := localizedStrings["9xf"]
            case 185: this.localizedName := localizedStrings["9cs"]
            case 186: this.localizedName := localizedStrings["9lw"]
            case 187: this.localizedName := localizedStrings["9tw"]
            case 188: this.localizedName := localizedStrings["9qr"]
            case 189: this.localizedName := localizedStrings["7ar"]
            case 190: this.localizedName := localizedStrings["7wb"]
            case 191: this.localizedName := localizedStrings["7xf"]
            case 192: this.localizedName := localizedStrings["7cs"]
            case 193: this.localizedName := localizedStrings["7lw"]
            case 194: this.localizedName := localizedStrings["7tw"]
            case 195: this.localizedName := localizedStrings["7qr"]
            case 196: this.localizedName := localizedStrings["7ha"]
            case 197: this.localizedName := localizedStrings["7ax"]
            case 198: this.localizedName := localizedStrings["72a"]
            case 199: this.localizedName := localizedStrings["7mp"]
            case 200: this.localizedName := localizedStrings["7wa"]
            case 201: this.localizedName := localizedStrings["7la"]
            case 202: this.localizedName := localizedStrings["7ba"]
            case 203: this.localizedName := localizedStrings["7bt"]
            case 204: this.localizedName := localizedStrings["7ga"]
            case 205: this.localizedName := localizedStrings["7gi"]
            case 206: this.localizedName := localizedStrings["7wn"]
            case 207: this.localizedName := localizedStrings["7yw"]
            case 208: this.localizedName := localizedStrings["7bw"]
            case 209: this.localizedName := localizedStrings["7gw"]
            case 210: this.localizedName := localizedStrings["7cl"]
            case 211: this.localizedName := localizedStrings["7sc"]
            case 212: this.localizedName := localizedStrings["7qs"]
            case 213: this.localizedName := localizedStrings["7ws"]
            case 214: this.localizedName := localizedStrings["7sp"]
            case 215: this.localizedName := localizedStrings["7ma"]
            case 216: this.localizedName := localizedStrings["7mt"]
            case 217: this.localizedName := localizedStrings["7fl"]
            case 218: this.localizedName := localizedStrings["7wh"]
            case 219: this.localizedName := localizedStrings["7m7"]
            case 220: this.localizedName := localizedStrings["7gm"]
            case 221: this.localizedName := localizedStrings["7ss"]
            case 222: this.localizedName := localizedStrings["7sm"]
            case 223: this.localizedName := localizedStrings["7sb"]
            case 224: this.localizedName := localizedStrings["7fc"]
            case 225: this.localizedName := localizedStrings["7cr"]
            case 226: this.localizedName := localizedStrings["7bs"]
            case 227: this.localizedName := localizedStrings["7ls"]
            case 228: this.localizedName := localizedStrings["7wd"]
            case 229: this.localizedName := localizedStrings["72h"]
            case 230: this.localizedName := localizedStrings["7cm"]
            case 231: this.localizedName := localizedStrings["7gs"]
            case 232: this.localizedName := localizedStrings["7b7"]
            case 233: this.localizedName := localizedStrings["7fb"]
            case 234: this.localizedName := localizedStrings["7gd"]
            case 235: this.localizedName := localizedStrings["7dg"]
            case 236: this.localizedName := localizedStrings["7di"]
            case 237: this.localizedName := localizedStrings["7kr"]
            case 238: this.localizedName := localizedStrings["7bl"]
            case 239: this.localizedName := localizedStrings["7tk"]
            case 240: this.localizedName := localizedStrings["7ta"]
            case 241: this.localizedName := localizedStrings["7bk"]
            case 242: this.localizedName := localizedStrings["7b8"]
            case 243: this.localizedName := localizedStrings["7ja"]
            case 244: this.localizedName := localizedStrings["7pi"]
            case 245: this.localizedName := localizedStrings["7s7"]
            case 246: this.localizedName := localizedStrings["7gl"]
            case 247: this.localizedName := localizedStrings["7ts"]
            case 248: this.localizedName := localizedStrings["7sr"]
            case 249: this.localizedName := localizedStrings["7tr"]
            case 250: this.localizedName := localizedStrings["7br"]
            case 251: this.localizedName := localizedStrings["7st"]
            case 252: this.localizedName := localizedStrings["7p7"]
            case 253: this.localizedName := localizedStrings["7o7"]
            case 254: this.localizedName := localizedStrings["7vo"]
            case 255: this.localizedName := localizedStrings["7s8"]
            case 256: this.localizedName := localizedStrings["7pa"]
            case 257: this.localizedName := localizedStrings["7h7"]
            case 258: this.localizedName := localizedStrings["7wc"]
            case 259: this.localizedName := localizedStrings["6ss"]
            case 260: this.localizedName := localizedStrings["6ls"]
            case 261: this.localizedName := localizedStrings["6cs"]
            case 262: this.localizedName := localizedStrings["6bs"]
            case 263: this.localizedName := localizedStrings["6ws"]
            case 264: this.localizedName := localizedStrings["6sb"]
            case 265: this.localizedName := localizedStrings["6hb"]
            case 266: this.localizedName := localizedStrings["6lb"]
            case 267: this.localizedName := localizedStrings["6cb"]
            case 268: this.localizedName := localizedStrings["6s7"]
            case 269: this.localizedName := localizedStrings["6l7"]
            case 270: this.localizedName := localizedStrings["6sw"]
            case 271: this.localizedName := localizedStrings["6lw"]
            case 272: this.localizedName := localizedStrings["6lx"]
            case 273: this.localizedName := localizedStrings["6mx"]
            case 274: this.localizedName := localizedStrings["6hx"]
            case 275: this.localizedName := localizedStrings["6rx"]
            case 276: this.localizedName := localizedStrings["ob1"]
            case 277: this.localizedName := localizedStrings["ob2"]
            case 278: this.localizedName := localizedStrings["ob3"]
            case 279: this.localizedName := localizedStrings["ob4"]
            case 280: this.localizedName := localizedStrings["ob5"]
            case 281: this.localizedName := localizedStrings["am1"]
            case 282: this.localizedName := localizedStrings["am2"]
            case 283: this.localizedName := localizedStrings["am3"]
            case 284: this.localizedName := localizedStrings["am4"]
            case 285: this.localizedName := localizedStrings["am5"]
            case 286: this.localizedName := localizedStrings["ob6"]
            case 287: this.localizedName := localizedStrings["ob7"]
            case 288: this.localizedName := localizedStrings["ob8"]
            case 289: this.localizedName := localizedStrings["ob9"]
            case 290: this.localizedName := localizedStrings["oba"]
            case 291: this.localizedName := localizedStrings["am6"]
            case 292: this.localizedName := localizedStrings["am7"]
            case 293: this.localizedName := localizedStrings["am8"]
            case 294: this.localizedName := localizedStrings["am9"]
            case 295: this.localizedName := localizedStrings["ama"]
            case 296: this.localizedName := localizedStrings["obb"]
            case 297: this.localizedName := localizedStrings["obc"]
            case 298: this.localizedName := localizedStrings["obd"]
            case 299: this.localizedName := localizedStrings["obe"]
            case 300: this.localizedName := localizedStrings["obf"]
            case 301: this.localizedName := localizedStrings["amb"]
            case 302: this.localizedName := localizedStrings["amc"]
            case 303: this.localizedName := localizedStrings["amd"]
            case 304: this.localizedName := localizedStrings["ame"]
            case 305: this.localizedName := localizedStrings["amf"]
            case 306: this.localizedName := localizedStrings["cap"]
            case 307: this.localizedName := localizedStrings["skp"]
            case 308: this.localizedName := localizedStrings["hlm"]
            case 309: this.localizedName := localizedStrings["fhl"]
            case 310: this.localizedName := localizedStrings["ghm"]
            case 311: this.localizedName := localizedStrings["crn"]
            case 312: this.localizedName := localizedStrings["msk"]
            case 313: this.localizedName := localizedStrings["qui"]
            case 314: this.localizedName := localizedStrings["lea"]
            case 315: this.localizedName := localizedStrings["hla"]
            case 316: this.localizedName := localizedStrings["stu"]
            case 317: this.localizedName := localizedStrings["rng"]
            case 318: this.localizedName := localizedStrings["scl"]
            case 319: this.localizedName := localizedStrings["chn"]
            case 320: this.localizedName := localizedStrings["brs"]
            case 321: this.localizedName := localizedStrings["spl"]
            case 322: this.localizedName := localizedStrings["plt"]
            case 323: this.localizedName := localizedStrings["fld"]
            case 324: this.localizedName := localizedStrings["gth"]
            case 325: this.localizedName := localizedStrings["ful"]
            case 326: this.localizedName := localizedStrings["aar"]
            case 327: this.localizedName := localizedStrings["ltp"]
            case 328: this.localizedName := localizedStrings["buc"]
            case 329: this.localizedName := localizedStrings["sml"]
            case 330: this.localizedName := localizedStrings["lrg"]
            case 331: this.localizedName := localizedStrings["kit"]
            case 332: this.localizedName := localizedStrings["tow"]
            case 333: this.localizedName := localizedStrings["gts"]
            case 334: this.localizedName := localizedStrings["lgl"]
            case 335: this.localizedName := localizedStrings["vgl"]
            case 336: this.localizedName := localizedStrings["mgl"]
            case 337: this.localizedName := localizedStrings["tgl"]
            case 338: this.localizedName := localizedStrings["hgl"]
            case 339: this.localizedName := localizedStrings["lbt"]
            case 340: this.localizedName := localizedStrings["vbt"]
            case 341: this.localizedName := localizedStrings["mbt"]
            case 342: this.localizedName := localizedStrings["tbt"]
            case 343: this.localizedName := localizedStrings["hbt"]
            case 344: this.localizedName := localizedStrings["lbl"]
            case 345: this.localizedName := localizedStrings["vbl"]
            case 346: this.localizedName := localizedStrings["mbl"]
            case 347: this.localizedName := localizedStrings["tbl"]
            case 348: this.localizedName := localizedStrings["hbl"]
            case 349: this.localizedName := localizedStrings["bhm"]
            case 350: this.localizedName := localizedStrings["bsh"]
            case 351: this.localizedName := localizedStrings["spk"]
            case 352: this.localizedName := localizedStrings["xap"]
            case 353: this.localizedName := localizedStrings["xkp"]
            case 354: this.localizedName := localizedStrings["xlm"]
            case 355: this.localizedName := localizedStrings["xhl"]
            case 356: this.localizedName := localizedStrings["xhm"]
            case 357: this.localizedName := localizedStrings["xrn"]
            case 358: this.localizedName := localizedStrings["xsk"]
            case 359: this.localizedName := localizedStrings["xui"]
            case 360: this.localizedName := localizedStrings["xea"]
            case 361: this.localizedName := localizedStrings["xla"]
            case 362: this.localizedName := localizedStrings["xtu"]
            case 363: this.localizedName := localizedStrings["xng"]
            case 364: this.localizedName := localizedStrings["xcl"]
            case 365: this.localizedName := localizedStrings["xhn"]
            case 366: this.localizedName := localizedStrings["xrs"]
            case 367: this.localizedName := localizedStrings["xpl"]
            case 368: this.localizedName := localizedStrings["xlt"]
            case 369: this.localizedName := localizedStrings["xld"]
            case 370: this.localizedName := localizedStrings["xth"]
            case 371: this.localizedName := localizedStrings["xul"]
            case 372: this.localizedName := localizedStrings["xar"]
            case 373: this.localizedName := localizedStrings["xtp"]
            case 374: this.localizedName := localizedStrings["xuc"]
            case 375: this.localizedName := localizedStrings["xml"]
            case 376: this.localizedName := localizedStrings["xrg"]
            case 377: this.localizedName := localizedStrings["xit"]
            case 378: this.localizedName := localizedStrings["xow"]
            case 379: this.localizedName := localizedStrings["xts"]
            case 380: this.localizedName := localizedStrings["xlg"]
            case 381: this.localizedName := localizedStrings["xvg"]
            case 382: this.localizedName := localizedStrings["xmg"]
            case 383: this.localizedName := localizedStrings["xtg"]
            case 384: this.localizedName := localizedStrings["xhg"]
            case 385: this.localizedName := localizedStrings["xlb"]
            case 386: this.localizedName := localizedStrings["xvb"]
            case 387: this.localizedName := localizedStrings["xmb"]
            case 388: this.localizedName := localizedStrings["xtb"]
            case 389: this.localizedName := localizedStrings["xhb"]
            case 390: this.localizedName := localizedStrings["zlb"]
            case 391: this.localizedName := localizedStrings["zvb"]
            case 392: this.localizedName := localizedStrings["zmb"]
            case 393: this.localizedName := localizedStrings["ztb"]
            case 394: this.localizedName := localizedStrings["zhb"]
            case 395: this.localizedName := localizedStrings["xh9"]
            case 396: this.localizedName := localizedStrings["xsh"]
            case 397: this.localizedName := localizedStrings["xpk"]
            case 398: this.localizedName := localizedStrings["dr1"]
            case 399: this.localizedName := localizedStrings["dr2"]
            case 400: this.localizedName := localizedStrings["dr3"]
            case 401: this.localizedName := localizedStrings["dr4"]
            case 402: this.localizedName := localizedStrings["dr5"]
            case 403: this.localizedName := localizedStrings["ba1"]
            case 404: this.localizedName := localizedStrings["ba2"]
            case 405: this.localizedName := localizedStrings["ba3"]
            case 406: this.localizedName := localizedStrings["ba4"]
            case 407: this.localizedName := localizedStrings["ba5"]
            case 408: this.localizedName := localizedStrings["pa1"]
            case 409: this.localizedName := localizedStrings["pa2"]
            case 410: this.localizedName := localizedStrings["pa3"]
            case 411: this.localizedName := localizedStrings["pa4"]
            case 412: this.localizedName := localizedStrings["pa5"]
            case 413: this.localizedName := localizedStrings["ne1"]
            case 414: this.localizedName := localizedStrings["ne2"]
            case 415: this.localizedName := localizedStrings["ne3"]
            case 416: this.localizedName := localizedStrings["ne4"]
            case 417: this.localizedName := localizedStrings["ne5"]
            case 418: this.localizedName := localizedStrings["ci0"]
            case 419: this.localizedName := localizedStrings["ci1"]
            case 420: this.localizedName := localizedStrings["ci2"]
            case 421: this.localizedName := localizedStrings["ci3"]
            case 422: this.localizedName := localizedStrings["uap"]
            case 423: this.localizedName := localizedStrings["ukp"]
            case 424: this.localizedName := localizedStrings["ulm"]
            case 425: this.localizedName := localizedStrings["uhl"]
            case 426: this.localizedName := localizedStrings["uhm"]
            case 427: this.localizedName := localizedStrings["urn"]
            case 428: this.localizedName := localizedStrings["usk"]
            case 429: this.localizedName := localizedStrings["uui"]
            case 430: this.localizedName := localizedStrings["uea"]
            case 431: this.localizedName := localizedStrings["ula"]
            case 432: this.localizedName := localizedStrings["utu"]
            case 433: this.localizedName := localizedStrings["ung"]
            case 434: this.localizedName := localizedStrings["ucl"]
            case 435: this.localizedName := localizedStrings["uhn"]
            case 436: this.localizedName := localizedStrings["urs"]
            case 437: this.localizedName := localizedStrings["upl"]
            case 438: this.localizedName := localizedStrings["ult"]
            case 439: this.localizedName := localizedStrings["uld"]
            case 440: this.localizedName := localizedStrings["uth"]
            case 441: this.localizedName := localizedStrings["uul"]
            case 442: this.localizedName := localizedStrings["uar"]
            case 443: this.localizedName := localizedStrings["utp"]
            case 444: this.localizedName := localizedStrings["uuc"]
            case 445: this.localizedName := localizedStrings["uml"]
            case 446: this.localizedName := localizedStrings["urg"]
            case 447: this.localizedName := localizedStrings["uit"]
            case 448: this.localizedName := localizedStrings["uow"]
            case 449: this.localizedName := localizedStrings["uts"]
            case 450: this.localizedName := localizedStrings["ulg"]
            case 451: this.localizedName := localizedStrings["uvg"]
            case 452: this.localizedName := localizedStrings["umg"]
            case 453: this.localizedName := localizedStrings["utg"]
            case 454: this.localizedName := localizedStrings["uhg"]
            case 455: this.localizedName := localizedStrings["ulb"]
            case 456: this.localizedName := localizedStrings["uvb"]
            case 457: this.localizedName := localizedStrings["umb"]
            case 458: this.localizedName := localizedStrings["utb"]
            case 459: this.localizedName := localizedStrings["uhb"]
            case 460: this.localizedName := localizedStrings["ulc"]
            case 461: this.localizedName := localizedStrings["uvc"]
            case 462: this.localizedName := localizedStrings["umc"]
            case 463: this.localizedName := localizedStrings["utc"]
            case 464: this.localizedName := localizedStrings["uhc"]
            case 465: this.localizedName := localizedStrings["uh9"]
            case 466: this.localizedName := localizedStrings["ush"]
            case 467: this.localizedName := localizedStrings["upk"]
            case 468: this.localizedName := localizedStrings["dr6"]
            case 469: this.localizedName := localizedStrings["dr7"]
            case 470: this.localizedName := localizedStrings["dr8"]
            case 471: this.localizedName := localizedStrings["dr9"]
            case 472: this.localizedName := localizedStrings["dra"]
            case 473: this.localizedName := localizedStrings["ba6"]
            case 474: this.localizedName := localizedStrings["ba7"]
            case 475: this.localizedName := localizedStrings["ba8"]
            case 476: this.localizedName := localizedStrings["ba9"]
            case 477: this.localizedName := localizedStrings["baa"]
            case 478: this.localizedName := localizedStrings["pa6"]
            case 479: this.localizedName := localizedStrings["pa7"]
            case 480: this.localizedName := localizedStrings["pa8"]
            case 481: this.localizedName := localizedStrings["pa9"]
            case 482: this.localizedName := localizedStrings["paa"]
            case 483: this.localizedName := localizedStrings["ne6"]
            case 484: this.localizedName := localizedStrings["ne7"]
            case 485: this.localizedName := localizedStrings["ne8"]
            case 486: this.localizedName := localizedStrings["ne9"]
            case 487: this.localizedName := localizedStrings["nea"]
            case 488: this.localizedName := localizedStrings["drb"]
            case 489: this.localizedName := localizedStrings["drc"]
            case 490: this.localizedName := localizedStrings["drd"]
            case 491: this.localizedName := localizedStrings["dre"]
            case 492: this.localizedName := localizedStrings["drf"]
            case 493: this.localizedName := localizedStrings["bab"]
            case 494: this.localizedName := localizedStrings["bac"]
            case 495: this.localizedName := localizedStrings["bad"]
            case 496: this.localizedName := localizedStrings["bae"]
            case 497: this.localizedName := localizedStrings["baf"]
            case 498: this.localizedName := localizedStrings["pab"]
            case 499: this.localizedName := localizedStrings["pac"]
            case 500: this.localizedName := localizedStrings["pad"]
            case 501: this.localizedName := localizedStrings["pae"]
            case 502: this.localizedName := localizedStrings["paf"]
            case 503: this.localizedName := localizedStrings["neb"]
            case 504: this.localizedName := localizedStrings["neg"]
            case 505: this.localizedName := localizedStrings["ned"]
            case 506: this.localizedName := localizedStrings["nee"]
            case 507: this.localizedName := localizedStrings["nef"]
            case 508: this.localizedName := localizedStrings["elx"]
            case 509: this.localizedName := localizedStrings["hpo"]
            case 510: this.localizedName := localizedStrings["mpo"]
            case 511: this.localizedName := localizedStrings["hpf"]
            case 512: this.localizedName := localizedStrings["mpf"]
            case 513: this.localizedName := localizedStrings["vps"]
            case 514: this.localizedName := localizedStrings["yps"]
            case 515: this.localizedName := localizedStrings["rvs"]
            case 516: this.localizedName := localizedStrings["rvl"]
            case 517: this.localizedName := localizedStrings["wms"]
            case 518: this.localizedName := localizedStrings["tbk"]
            case 519: this.localizedName := localizedStrings["ibk"]
            case 520: this.localizedName := localizedStrings["amu"]
            case 521: this.localizedName := localizedStrings["vip"]
            case 522: this.localizedName := localizedStrings["rin"]
            case 523: this.localizedName := localizedStrings["gld"]
            case 524: this.localizedName := localizedStrings["bks"]
            case 525: this.localizedName := localizedStrings["bkd"]
            case 526: this.localizedName := localizedStrings["aqv"]
            case 527: this.localizedName := localizedStrings["tch"]
            case 528: this.localizedName := localizedStrings["cqv"]
            case 529: this.localizedName := localizedStrings["tsc"]
            case 530: this.localizedName := localizedStrings["isc"]
            case 531: this.localizedName := localizedStrings["hrt"]
            case 532: this.localizedName := localizedStrings["brz"]
            case 533: this.localizedName := localizedStrings["jaw"]
            case 534: this.localizedName := localizedStrings["eyz"]
            case 535: this.localizedName := localizedStrings["hrn"]
            case 536: this.localizedName := localizedStrings["tal"]
            case 537: this.localizedName := localizedStrings["flg"]
            case 538: this.localizedName := localizedStrings["fng"]
            case 539: this.localizedName := localizedStrings["qll"]
            case 540: this.localizedName := localizedStrings["sol"]
            case 541: this.localizedName := localizedStrings["scz"]
            case 542: this.localizedName := localizedStrings["spe"]
            case 543: this.localizedName := localizedStrings["key"]
            case 544: this.localizedName := localizedStrings["luv"]
            case 545: this.localizedName := localizedStrings["xyz"]
            case 546: this.localizedName := localizedStrings["j34"]
            case 547: this.localizedName := localizedStrings["g34"]
            case 548: this.localizedName := localizedStrings["bbb"]
            case 549: this.localizedName := localizedStrings["box"]
            case 550: this.localizedName := localizedStrings["tr1"]
            case 551: this.localizedName := localizedStrings["mss"]
            case 552: this.localizedName := localizedStrings["ass"]
            case 553: this.localizedName := localizedStrings["qey"]
            case 554: this.localizedName := localizedStrings["qhr"]
            case 555: this.localizedName := localizedStrings["qbr"]
            case 556: this.localizedName := localizedStrings["ear"]
            case 557: this.localizedName := localizedStrings["gcv"]
            case 558: this.localizedName := localizedStrings["gfv"]
            case 559: this.localizedName := localizedStrings["gsv"]
            case 560: this.localizedName := localizedStrings["gzv"]
            case 561: this.localizedName := localizedStrings["gpv"]
            case 562: this.localizedName := localizedStrings["gcy"]
            case 563: this.localizedName := localizedStrings["gfy"]
            case 564: this.localizedName := localizedStrings["gsy"]
            case 565: this.localizedName := localizedStrings["gly"]
            case 566: this.localizedName := localizedStrings["gpy"]
            case 567: this.localizedName := localizedStrings["gcb"]
            case 568: this.localizedName := localizedStrings["gfb"]
            case 569: this.localizedName := localizedStrings["gsb"]
            case 570: this.localizedName := localizedStrings["glb"]
            case 571: this.localizedName := localizedStrings["gpb"]
            case 572: this.localizedName := localizedStrings["gcg"]
            case 573: this.localizedName := localizedStrings["gfg"]
            case 574: this.localizedName := localizedStrings["gsg"]
            case 575: this.localizedName := localizedStrings["glg"]
            case 576: this.localizedName := localizedStrings["gpg"]
            case 577: this.localizedName := localizedStrings["gcr"]
            case 578: this.localizedName := localizedStrings["gfr"]
            case 579: this.localizedName := localizedStrings["gsr"]
            case 580: this.localizedName := localizedStrings["glr"]
            case 581: this.localizedName := localizedStrings["gpr"]
            case 582: this.localizedName := localizedStrings["gcw"]
            case 583: this.localizedName := localizedStrings["gfw"]
            case 584: this.localizedName := localizedStrings["gsw"]
            case 585: this.localizedName := localizedStrings["glw"]
            case 586: this.localizedName := localizedStrings["gpw"]
            case 587: this.localizedName := localizedStrings["hp1"]
            case 588: this.localizedName := localizedStrings["hp2"]
            case 589: this.localizedName := localizedStrings["hp3"]
            case 590: this.localizedName := localizedStrings["hp4"]
            case 591: this.localizedName := localizedStrings["hp5"]
            case 592: this.localizedName := localizedStrings["mp1"]
            case 593: this.localizedName := localizedStrings["mp2"]
            case 594: this.localizedName := localizedStrings["mp3"]
            case 595: this.localizedName := localizedStrings["mp4"]
            case 596: this.localizedName := localizedStrings["mp5"]
            case 597: this.localizedName := localizedStrings["skc"]
            case 598: this.localizedName := localizedStrings["skf"]
            case 599: this.localizedName := localizedStrings["sku"]
            case 600: this.localizedName := localizedStrings["skl"]
            case 601: this.localizedName := localizedStrings["skz"]
            case 602: this.localizedName := localizedStrings["hrb"]
            case 603: this.localizedName := localizedStrings["cm1"]
            case 604: this.localizedName := localizedStrings["cm2"]
            case 605: this.localizedName := localizedStrings["cm3"]
            case 606: this.localizedName := localizedStrings["rps"]
            case 607: this.localizedName := localizedStrings["rpl"]
            case 608: this.localizedName := localizedStrings["bps"]
            case 609: this.localizedName := localizedStrings["bpl"]
            case 610: this.localizedName := localizedStrings["r01"]
            case 611: this.localizedName := localizedStrings["r02"]
            case 612: this.localizedName := localizedStrings["r03"]
            case 613: this.localizedName := localizedStrings["r04"]
            case 614: this.localizedName := localizedStrings["r05"]
            case 615: this.localizedName := localizedStrings["r06"]
            case 616: this.localizedName := localizedStrings["r07"]
            case 617: this.localizedName := localizedStrings["r08"]
            case 618: this.localizedName := localizedStrings["r09"]
            case 619: this.localizedName := localizedStrings["r10"]
            case 620: this.localizedName := localizedStrings["r11"]
            case 621: this.localizedName := localizedStrings["r12"]
            case 622: this.localizedName := localizedStrings["r13"]
            case 623: this.localizedName := localizedStrings["r14"]
            case 624: this.localizedName := localizedStrings["r15"]
            case 625: this.localizedName := localizedStrings["r16"]
            case 626: this.localizedName := localizedStrings["r17"]
            case 627: this.localizedName := localizedStrings["r18"]
            case 628: this.localizedName := localizedStrings["r19"]
            case 629: this.localizedName := localizedStrings["r20"]
            case 630: this.localizedName := localizedStrings["r21"]
            case 631: this.localizedName := localizedStrings["r22"]
            case 632: this.localizedName := localizedStrings["r23"]
            case 633: this.localizedName := localizedStrings["r24"]
            case 634: this.localizedName := localizedStrings["r25"]
            case 635: this.localizedName := localizedStrings["r26"]
            case 636: this.localizedName := localizedStrings["r27"]
            case 637: this.localizedName := localizedStrings["r28"]
            case 638: this.localizedName := localizedStrings["r29"]
            case 639: this.localizedName := localizedStrings["r30"]
            case 640: this.localizedName := localizedStrings["r31"]
            case 641: this.localizedName := localizedStrings["r32"]
            case 642: this.localizedName := localizedStrings["r33"]
            case 643: this.localizedName := localizedStrings["jew"]
            case 644: this.localizedName := localizedStrings["ice"]
            case 645: this.localizedName := localizedStrings["0sc"]
            case 646: this.localizedName := localizedStrings["tr2"]
            case 647: this.localizedName := localizedStrings["pk1"]
            case 648: this.localizedName := localizedStrings["pk2"]
            case 649: this.localizedName := localizedStrings["pk3"]
            case 650: this.localizedName := localizedStrings["dhn"]
            case 651: this.localizedName := localizedStrings["bey"]
            case 652: this.localizedName := localizedStrings["mbr"]
            case 653: this.localizedName := localizedStrings["toa"]
            case 654: this.localizedName := localizedStrings["tes"]
            case 655: this.localizedName := localizedStrings["ceh"]
            case 656: this.localizedName := localizedStrings["bet"]
            case 657: this.localizedName := localizedStrings["fed"]
            case 658: this.localizedName := localizedStrings["std"]
        }
    }
    
    setItemName(txtFileNo) {
        switch (txtFileNo) {
            case 0: this.name := "Hand Axe" 
            case 1: this.name := "Axe" 
            case 2: this.name := "Double Axe" 
            case 3: this.name := "Military Pick" 
            case 4: this.name := "War Axe" 
            case 5: this.name := "Large Axe" 
            case 6: this.name := "Broad Axe" 
            case 7: this.name := "Battle Axe" 
            case 8: this.name := "Great Axe" 
            case 9: this.name := "Giant Axe" 
            case 10: this.name := "Wand" 
            case 11: this.name := "Yew Wand" 
            case 12: this.name := "Bone Wand" 
            case 13: this.name := "Grim Wand" 
            case 14: this.name := "Club" 
            case 15: this.name := "Scepter" 
            case 16: this.name := "Grand Scepter" 
            case 17: this.name := "War Scepter" 
            case 18: this.name := "Spiked Club" 
            case 19: this.name := "Mace" 
            case 20: this.name := "Morning Star" 
            case 21: this.name := "Flail" 
            case 22: this.name := "War Hammer" 
            case 23: this.name := "Maul" 
            case 24: this.name := "Great Maul" 
            case 25: this.name := "Short Sword" 
            case 26: this.name := "Scimitar" 
            case 27: this.name := "Saber" 
            case 28: this.name := "Falchion" 
            case 29: this.name := "Crystal Sword" 
            case 30: this.name := "Broad Sword" 
            case 31: this.name := "Long Sword" 
            case 32: this.name := "War Sword" 
            case 33: this.name := "Two-Handed Sword" 
            case 34: this.name := "Claymore" 
            case 35: this.name := "Giant Sword" 
            case 36: this.name := "Bastard Sword" 
            case 37: this.name := "Flamberge" 
            case 38: this.name := "Great Sword" 
            case 39: this.name := "Dagger" 
            case 40: this.name := "Dirk" 
            case 41: this.name := "Kriss" 
            case 42: this.name := "Blade" 
            case 43: this.name := "Throwing Knife" 
            case 44: this.name := "Throwing Axe" 
            case 45: this.name := "Balanced Knife" 
            case 46: this.name := "Balanced Axe" 
            case 47: this.name := "Javelin" 
            case 48: this.name := "Pilum" 
            case 49: this.name := "Short Spear" 
            case 50: this.name := "Glaive" 
            case 51: this.name := "Throwing Spear" 
            case 52: this.name := "Spear" 
            case 53: this.name := "Trident" 
            case 54: this.name := "Brandistock" 
            case 55: this.name := "Spetum" 
            case 56: this.name := "Pike" 
            case 57: this.name := "Bardiche" 
            case 58: this.name := "Voulge" 
            case 59: this.name := "Scythe" 
            case 60: this.name := "Poleaxe" 
            case 61: this.name := "Halberd" 
            case 62: this.name := "War Scythe" 
            case 63: this.name := "Short Staff" 
            case 64: this.name := "Long Staff" 
            case 65: this.name := "Gnarled Staff" 
            case 66: this.name := "Battle Staff" 
            case 67: this.name := "War Staff" 
            case 68: this.name := "Short Bow" 
            case 69: this.name := "Hunter's Bow" 
            case 70: this.name := "Long Bow" 
            case 71: this.name := "Composite Bow" 
            case 72: this.name := "Short Battle Bow" 
            case 73: this.name := "Long Battle Bow" 
            case 74: this.name := "Short War Bow" 
            case 75: this.name := "Long War Bow" 
            case 76: this.name := "Light Crossbow" 
            case 77: this.name := "Crossbow" 
            case 78: this.name := "Heavy Crossbow" 
            case 79: this.name := "Repeating Crossbow" 
            case 80: this.name := "Rancid Gas Potion" 
            case 81: this.name := "Oil Potion" 
            case 82: this.name := "Choking Gas Potion" 
            case 83: this.name := "Exploding Potion" 
            case 84: this.name := "Strangling Gas Potion" 
            case 85: this.name := "Fulminating Potion" 
            case 86: this.name := "Decoy Gidbinn" 
            case 87: this.name := "The Gidbinn" 
            case 88: this.name := "Wirt's Leg" 
            case 89: this.name := "Horadric Malus" 
            case 90: this.name := "Hellforge Hammer" 
            case 91: this.name := "Horadric Staff" 
            case 92: this.name := "Staff of Kings" 
            case 93: this.name := "Hatchet" 
            case 94: this.name := "Cleaver" 
            case 95: this.name := "Twin Axe" 
            case 96: this.name := "Crowbill" 
            case 97: this.name := "Naga" 
            case 98: this.name := "Military Axe" 
            case 99: this.name := "Bearded Axe" 
            case 100: this.name := "Tabar" 
            case 101: this.name := "Gothic Axe" 
            case 102: this.name := "Ancient Axe" 
            case 103: this.name := "Burnt Wand" 
            case 104: this.name := "Petrified Wand" 
            case 105: this.name := "Tomb Wand" 
            case 106: this.name := "Grave Wand" 
            case 107: this.name := "Cudgel" 
            case 108: this.name := "Rune Scepter" 
            case 109: this.name := "Holy Water Sprinkler" 
            case 110: this.name := "Divine Scepter" 
            case 111: this.name := "Barbed Club" 
            case 112: this.name := "Flanged Mace" 
            case 113: this.name := "Jagged Star" 
            case 114: this.name := "Knout" 
            case 115: this.name := "Battle Hammer" 
            case 116: this.name := "War Club" 
            case 117: this.name := "Martel de Fer" 
            case 118: this.name := "Gladius" 
            case 119: this.name := "Cutlass" 
            case 120: this.name := "Shamshir" 
            case 121: this.name := "Tulwar" 
            case 122: this.name := "Dimensional Blade" 
            case 123: this.name := "Battle Sword" 
            case 124: this.name := "Rune Sword" 
            case 125: this.name := "Ancient Sword" 
            case 126: this.name := "Espandon" 
            case 127: this.name := "Dacian Falx" 
            case 128: this.name := "Tusk Sword" 
            case 129: this.name := "Gothic Sword" 
            case 130: this.name := "Zweihander" 
            case 131: this.name := "Executioner Sword" 
            case 132: this.name := "Poignard" 
            case 133: this.name := "Rondel" 
            case 134: this.name := "Cinquedeas" 
            case 135: this.name := "Stilleto" 
            case 136: this.name := "Battle Dart" 
            case 137: this.name := "Francisca" 
            case 138: this.name := "War Dart" 
            case 139: this.name := "Hurlbat" 
            case 140: this.name := "War Javelin" 
            case 141: this.name := "Great Pilum" 
            case 142: this.name := "Simbilan" 
            case 143: this.name := "Spiculum" 
            case 144: this.name := "Harpoon" 
            case 145: this.name := "War Spear" 
            case 146: this.name := "Fuscina" 
            case 147: this.name := "War Fork" 
            case 148: this.name := "Yari" 
            case 149: this.name := "Lance" 
            case 150: this.name := "Lochaber Axe" 
            case 151: this.name := "Bill" 
            case 152: this.name := "Battle Scythe" 
            case 153: this.name := "Partizan" 
            case 154: this.name := "Bec-de-Corbin" 
            case 155: this.name := "Grim Scythe" 
            case 156: this.name := "Jo Staff" 
            case 157: this.name := "Quarterstaff" 
            case 158: this.name := "Cedar Staff" 
            case 159: this.name := "Gothic Staff" 
            case 160: this.name := "Rune Staff" 
            case 161: this.name := "Edge Bow" 
            case 162: this.name := "Razor Bow" 
            case 163: this.name := "Cedar Bow" 
            case 164: this.name := "Double Bow" 
            case 165: this.name := "Short Siege Bow" 
            case 166: this.name := "Long Siege Bow" 
            case 167: this.name := "Rune Bow" 
            case 168: this.name := "Gothic Bow" 
            case 169: this.name := "Arbalest" 
            case 170: this.name := "Siege Crossbow" 
            case 171: this.name := "Ballista" 
            case 172: this.name := "Chu-Ko-Nu" 
            case 173: this.name := "Khalim's Flail" 
            case 174: this.name := "Khalim's Will" 
            case 175: this.name := "Katar" 
            case 176: this.name := "Wrist Blade" 
            case 177: this.name := "Hatchet Hands" 
            case 178: this.name := "Cestus" 
            case 179: this.name := "Claws" 
            case 180: this.name := "Blade Talons" 
            case 181: this.name := "Scissors Katar" 
            case 182: this.name := "Quhab" 
            case 183: this.name := "Wrist Spike" 
            case 184: this.name := "Fascia" 
            case 185: this.name := "Hand Scythe" 
            case 186: this.name := "Greater Claws" 
            case 187: this.name := "Greater Talons" 
            case 188: this.name := "Scissors Quhab" 
            case 189: this.name := "Suwayyah" 
            case 190: this.name := "Wrist Sword" 
            case 191: this.name := "War Fist" 
            case 192: this.name := "Battle Cestus" 
            case 193: this.name := "Feral Claws" 
            case 194: this.name := "Runic Talons" 
            case 195: this.name := "Scissors Suwayyah" 
            case 196: this.name := "Tomahawk" 
            case 197: this.name := "Small Crescent" 
            case 198: this.name := "Ettin Axe" 
            case 199: this.name := "War Spike" 
            case 200: this.name := "Berserker Axe" 
            case 201: this.name := "Feral Axe" 
            case 202: this.name := "Silver-edged Axe" 
            case 203: this.name := "Decapitator" 
            case 204: this.name := "Champion Axe" 
            case 205: this.name := "Glorious Axe" 
            case 206: this.name := "Polished Wand" 
            case 207: this.name := "Ghost Wand" 
            case 208: this.name := "Lich Wand" 
            case 209: this.name := "Unearthed Wand" 
            case 210: this.name := "Truncheon" 
            case 211: this.name := "Mighty Scepter" 
            case 212: this.name := "Seraph Rod" 
            case 213: this.name := "Caduceus" 
            case 214: this.name := "Tyrant Club" 
            case 215: this.name := "Reinforced Mace" 
            case 216: this.name := "Devil Star" 
            case 217: this.name := "Scourge" 
            case 218: this.name := "Legendary Mallet" 
            case 219: this.name := "Ogre Maul" 
            case 220: this.name := "Thunder Maul" 
            case 221: this.name := "Falcata" 
            case 222: this.name := "Ataghan" 
            case 223: this.name := "Elegant Blade" 
            case 224: this.name := "Hydra Edge" 
            case 225: this.name := "Phase Blade" 
            case 226: this.name := "Conquest Sword" 
            case 227: this.name := "Cryptic Sword" 
            case 228: this.name := "Mythical Sword" 
            case 229: this.name := "Legend Sword" 
            case 230: this.name := "Highland Blade" 
            case 231: this.name := "Balrog Blade" 
            case 232: this.name := "Champion Sword" 
            case 233: this.name := "Colossal Sword" 
            case 234: this.name := "Colossus Blade" 
            case 235: this.name := "Bone Knife" 
            case 236: this.name := "Mithral Point" 
            case 237: this.name := "Fanged Knife" 
            case 238: this.name := "Legend Spike" 
            case 239: this.name := "Flying Knife" 
            case 240: this.name := "Flying Axe" 
            case 241: this.name := "Winged Knife" 
            case 242: this.name := "Winged Axe" 
            case 243: this.name := "Hyperion Javelin" 
            case 244: this.name := "Stygian Pilum" 
            case 245: this.name := "Balrog Spear" 
            case 246: this.name := "Ghost Glaive" 
            case 247: this.name := "Winged Harpoon" 
            case 248: this.name := "Hyperion Spear" 
            case 249: this.name := "Stygian Pike" 
            case 250: this.name := "Mancatcher" 
            case 251: this.name := "Ghost Spear" 
            case 252: this.name := "War Pike" 
            case 253: this.name := "Ogre Axe" 
            case 254: this.name := "Colossus Voulge" 
            case 255: this.name := "Thresher" 
            case 256: this.name := "Cryptic Axe" 
            case 257: this.name := "Great Poleaxe" 
            case 258: this.name := "Giant Thresher" 
            case 259: this.name := "Walking Stick" 
            case 260: this.name := "Stalagmite" 
            case 261: this.name := "Elder Staff" 
            case 262: this.name := "Shillelagh" 
            case 263: this.name := "Archon Staff" 
            case 264: this.name := "Spider Bow" 
            case 265: this.name := "Blade Bow" 
            case 266: this.name := "Shadow Bow" 
            case 267: this.name := "Great Bow" 
            case 268: this.name := "Diamond Bow" 
            case 269: this.name := "Crusader Bow" 
            case 270: this.name := "Ward Bow" 
            case 271: this.name := "Hydra Bow" 
            case 272: this.name := "Pellet Bow" 
            case 273: this.name := "Gorgon Crossbow" 
            case 274: this.name := "Colossus Crossbow" 
            case 275: this.name := "Demon Crossbow" 
            case 276: this.name := "Eagle Orb" 
            case 277: this.name := "Sacred Globe" 
            case 278: this.name := "Smoked Sphere" 
            case 279: this.name := "Clasped Orb" 
            case 280: this.name := "Jared's Stone" 
            case 281: this.name := "Stag Bow" 
            case 282: this.name := "Reflex Bow" 
            case 283: this.name := "Maiden Spear" 
            case 284: this.name := "Maiden Pike" 
            case 285: this.name := "Maiden Javelin" 
            case 286: this.name := "Glowing Orb" 
            case 287: this.name := "Crystalline Globe" 
            case 288: this.name := "Cloudy Sphere" 
            case 289: this.name := "Sparkling Ball" 
            case 290: this.name := "Swirling Crystal" 
            case 291: this.name := "Ashwood Bow" 
            case 292: this.name := "Ceremonial Bow" 
            case 293: this.name := "Ceremonial Spear" 
            case 294: this.name := "Ceremonial Pike" 
            case 295: this.name := "Ceremonial Javelin" 
            case 296: this.name := "Heavenly Stone" 
            case 297: this.name := "Eldritch Orb" 
            case 298: this.name := "Demon Heart" 
            case 299: this.name := "Vortex Orb" 
            case 300: this.name := "Dimensional Shard" 
            case 301: this.name := "Matriarchal Bow" 
            case 302: this.name := "Grand Matron Bow" 
            case 303: this.name := "Matriarchal Spear" 
            case 304: this.name := "Matriarchal Pike" 
            case 305: this.name := "Matriarchal Javelin" 
            case 306: this.name := "Cap" 
            case 307: this.name := "Skull Cap" 
            case 308: this.name := "Helm" 
            case 309: this.name := "Full Helm" 
            case 310: this.name := "Great Helm" 
            case 311: this.name := "Crown" 
            case 312: this.name := "Mask" 
            case 313: this.name := "Quilted Armor" 
            case 314: this.name := "Leather Armor" 
            case 315: this.name := "Hard Leather Armor" 
            case 316: this.name := "Studded Leather" 
            case 317: this.name := "Ring Mail" 
            case 318: this.name := "Scale Mail" 
            case 319: this.name := "Chain Mail" 
            case 320: this.name := "Breast Plate" 
            case 321: this.name := "Splint Mail" 
            case 322: this.name := "Plate Mail" 
            case 323: this.name := "Field Plate" 
            case 324: this.name := "Gothic Plate" 
            case 325: this.name := "Full Plate Mail" 
            case 326: this.name := "Ancient Armor" 
            case 327: this.name := "Light Plate" 
            case 328: this.name := "Buckler" 
            case 329: this.name := "Small Shield" 
            case 330: this.name := "Large Shield" 
            case 331: this.name := "Kite Shield" 
            case 332: this.name := "Tower Shield" 
            case 333: this.name := "Gothic Shield" 
            case 334: this.name := "Leather Gloves" 
            case 335: this.name := "Heavy Gloves" 
            case 336: this.name := "Chain Gloves" 
            case 337: this.name := "Light Gauntlets" 
            case 338: this.name := "Gauntlets" 
            case 339: this.name := "Boots" 
            case 340: this.name := "Heavy Boots" 
            case 341: this.name := "Chain Boots" 
            case 342: this.name := "Light Plated Boots" 
            case 343: this.name := "Greaves" 
            case 344: this.name := "Sash" 
            case 345: this.name := "Light Belt" 
            case 346: this.name := "Belt" 
            case 347: this.name := "Heavy Belt" 
            case 348: this.name := "Plated Belt" 
            case 349: this.name := "Bone Helm" 
            case 350: this.name := "Bone Shield" 
            case 351: this.name := "Spiked Shield" 
            case 352: this.name := "War Hat" 
            case 353: this.name := "Sallet" 
            case 354: this.name := "Casque" 
            case 355: this.name := "Basinet" 
            case 356: this.name := "Winged Helm" 
            case 357: this.name := "Grand Crown" 
            case 358: this.name := "Death Mask" 
            case 359: this.name := "Ghost Armor" 
            case 360: this.name := "Serpentskin Armor" 
            case 361: this.name := "Demonhide Armor" 
            case 362: this.name := "Trellised Armor" 
            case 363: this.name := "Linked Mail" 
            case 364: this.name := "Tigulated Mail" 
            case 365: this.name := "Mesh Armor" 
            case 366: this.name := "Cuirass" 
            case 367: this.name := "Russet Armor" 
            case 368: this.name := "Templar Coat" 
            case 369: this.name := "Sharktooth Armor" 
            case 370: this.name := "Embossed Plate" 
            case 371: this.name := "Chaos Armor" 
            case 372: this.name := "Ornate Armor" 
            case 373: this.name := "Mage Plate" 
            case 374: this.name := "Defender" 
            case 375: this.name := "Round Shield" 
            case 376: this.name := "Scutum" 
            case 377: this.name := "Dragon Shield" 
            case 378: this.name := "Pavise" 
            case 379: this.name := "Ancient Shield" 
            case 380: this.name := "Demonhide Gloves" 
            case 381: this.name := "Sharkskin Gloves" 
            case 382: this.name := "Heavy Bracers" 
            case 383: this.name := "Battle Gauntlets" 
            case 384: this.name := "War Gauntlets" 
            case 385: this.name := "Demonhide Boots" 
            case 386: this.name := "Sharkskin Boots" 
            case 387: this.name := "Mesh Boots" 
            case 388: this.name := "Battle Boots" 
            case 389: this.name := "War Boots" 
            case 390: this.name := "Demonhide Sash" 
            case 391: this.name := "Sharkskin Belt" 
            case 392: this.name := "Mesh Belt" 
            case 393: this.name := "Battle Belt" 
            case 394: this.name := "War Belt" 
            case 395: this.name := "Grim Helm" 
            case 396: this.name := "Grim Shield" 
            case 397: this.name := "Barbed Shield" 
            case 398: this.name := "Wolf Head" 
            case 399: this.name := "Hawk Helm" 
            case 400: this.name := "Antlers" 
            case 401: this.name := "Falcon Mask" 
            case 402: this.name := "Spirit Mask" 
            case 403: this.name := "Jawbone Cap" 
            case 404: this.name := "Fanged Helm" 
            case 405: this.name := "Horned Helm" 
            case 406: this.name := "Assault Helmet" 
            case 407: this.name := "Avenger Guard" 
            case 408: this.name := "Targe" 
            case 409: this.name := "Rondache" 
            case 410: this.name := "Heraldic Shield" 
            case 411: this.name := "Aerin Shield" 
            case 412: this.name := "Crown Shield" 
            case 413: this.name := "Preserved Head" 
            case 414: this.name := "Zombie Head" 
            case 415: this.name := "Unraveller Head" 
            case 416: this.name := "Gargoyle Head" 
            case 417: this.name := "Demon Head" 
            case 418: this.name := "Circlet" 
            case 419: this.name := "Coronet" 
            case 420: this.name := "Tiara" 
            case 421: this.name := "Diadem" 
            case 422: this.name := "Shako" 
            case 423: this.name := "Hydraskull" 
            case 424: this.name := "Armet" 
            case 425: this.name := "Giant Conch" 
            case 426: this.name := "Spired Helm" 
            case 427: this.name := "Corona" 
            case 428: this.name := "Demonhead" 
            case 429: this.name := "Dusk Shroud" 
            case 430: this.name := "Wyrmhide" 
            case 431: this.name := "Scarab Husk" 
            case 432: this.name := "Wire Fleece" 
            case 433: this.name := "Diamond Mail" 
            case 434: this.name := "Loricated Mail" 
            case 435: this.name := "Boneweave" 
            case 436: this.name := "Great Hauberk" 
            case 437: this.name := "Balrog Skin" 
            case 438: this.name := "Hellforge Plate" 
            case 439: this.name := "Kraken Shell" 
            case 440: this.name := "Lacquered Plate" 
            case 441: this.name := "Shadow Plate" 
            case 442: this.name := "Sacred Armor" 
            case 443: this.name := "Archon Plate" 
            case 444: this.name := "Heater" 
            case 445: this.name := "Luna" 
            case 446: this.name := "Hyperion" 
            case 447: this.name := "Monarch" 
            case 448: this.name := "Aegis" 
            case 449: this.name := "Ward" 
            case 450: this.name := "Bramble Mitts" 
            case 451: this.name := "Vampirebone Gloves" 
            case 452: this.name := "Vambraces" 
            case 453: this.name := "Crusader Gauntlets" 
            case 454: this.name := "Ogre Gauntlets" 
            case 455: this.name := "Wyrmhide Boots" 
            case 456: this.name := "Scarabshell Boots" 
            case 457: this.name := "Boneweave Boots" 
            case 458: this.name := "Mirrored Boots" 
            case 459: this.name := "Myrmidon Greaves" 
            case 460: this.name := "Spiderweb Sash" 
            case 461: this.name := "Vampirefang Belt" 
            case 462: this.name := "Mithril Coil" 
            case 463: this.name := "Troll Belt" 
            case 464: this.name := "Colossus Girdle" 
            case 465: this.name := "Bone Visage" 
            case 466: this.name := "Troll Nest" 
            case 467: this.name := "Blade Barrier" 
            case 468: this.name := "Alpha Helm" 
            case 469: this.name := "Griffon Headress" 
            case 470: this.name := "Hunter's Guise" 
            case 471: this.name := "Sacred Feathers" 
            case 472: this.name := "Totemic Mask" 
            case 473: this.name := "Jawbone Visor" 
            case 474: this.name := "Lion Helm" 
            case 475: this.name := "Rage Mask" 
            case 476: this.name := "Savage Helmet" 
            case 477: this.name := "Slayer Guard" 
            case 478: this.name := "Akaran Targe" 
            case 479: this.name := "Akaran Rondache" 
            case 480: this.name := "Protector Shield" 
            case 481: this.name := "Gilded Shield" 
            case 482: this.name := "Royal Shield" 
            case 483: this.name := "Mummified Trophy" 
            case 484: this.name := "Fetish Trophy" 
            case 485: this.name := "Sexton Trophy" 
            case 486: this.name := "Cantor Trophy" 
            case 487: this.name := "Heirophant Trophy" 
            case 488: this.name := "Blood Spirit" 
            case 489: this.name := "Sun Spirit" 
            case 490: this.name := "Earth Spirit" 
            case 491: this.name := "Sky Spirit" 
            case 492: this.name := "Dream Spirit" 
            case 493: this.name := "Carnage Helm" 
            case 494: this.name := "Fury Visor" 
            case 495: this.name := "Destroyer Helm" 
            case 496: this.name := "Conqueror Crown" 
            case 497: this.name := "Guardian Crown" 
            case 498: this.name := "Sacred Targe" 
            case 499: this.name := "Sacred Rondache" 
            case 500: this.name := "Ancient Shield" 
            case 501: this.name := "Zakarum Shield" 
            case 502: this.name := "Vortex Shield" 
            case 503: this.name := "Minion Skull" 
            case 504: this.name := "Hellspawn Skull" 
            case 505: this.name := "Overseer Skull" 
            case 506: this.name := "Succubus Skull" 
            case 507: this.name := "Bloodlord Skull" 
            case 508: this.name := "Elixir" 
            case 509: this.name := "Healing Potion" 
            case 510: this.name := "Mana Potion" 
            case 511: this.name := "Full Healing Potion" 
            case 512: this.name := "Full Mana Potion" 
            case 513: this.name := "Stamina Potion" 
            case 514: this.name := "Antidote Potion" 
            case 515: this.name := "Rejuvenation Potion" 
            case 516: this.name := "Full Rejuvenation Potion" 
            case 517: this.name := "Thawing Potion" 
            case 518: this.name := "Tome of Town Portal" 
            case 519: this.name := "Tome of Identify" 
            case 520: this.name := "Amulet" 
            case 521: this.name := "Amulet of the Viper" 
            case 522: this.name := "Ring" 
            case 523: this.name := "Gold" 
            case 524: this.name := "Scroll of Inifuss" 
            case 525: this.name := "Key to the Cairn Stones" 
            case 526: this.name := "Arrows" 
            case 527: this.name := "Torch" 
            case 528: this.name := "Bolts" 
            case 529: this.name := "Scroll of Town Portal" 
            case 530: this.name := "Scroll of Identify" 
            case 531: this.name := "Heart" 
            case 532: this.name := "Brain" 
            case 533: this.name := "Jawbone" 
            case 534: this.name := "Eye" 
            case 535: this.name := "Horn" 
            case 536: this.name := "Tail" 
            case 537: this.name := "Flag" 
            case 538: this.name := "Fang" 
            case 539: this.name := "Quill" 
            case 540: this.name := "Soul" 
            case 541: this.name := "Scalp" 
            case 542: this.name := "Spleen" 
            case 543: this.name := "Key" 
            case 544: this.name := "The Black Tower Key" 
            case 545: this.name := "Potion of Life" 
            case 546: this.name := "A Jade Figurine" 
            case 547: this.name := "The Golden Bird" 
            case 548: this.name := "Lam Esen's Tome" 
            case 549: this.name := "Horadric Cube" 
            case 550: this.name := "Horadric Scroll" 
            case 551: this.name := "Mephisto's Soulstone" 
            case 552: this.name := "Book of Skill" 
            case 553: this.name := "Khalim's Eye" 
            case 554: this.name := "Khalim's Heart" 
            case 555: this.name := "Khalim's Brain" 
            case 556: this.name := "Ear" 
            case 557: this.name := "Chipped Amethyst" 
            case 558: this.name := "Flawed Amethyst" 
            case 559: this.name := "Amethyst" 
            case 560: this.name := "Flawless Amethyst" 
            case 561: this.name := "Perfect Amethyst" 
            case 562: this.name := "Chipped Topaz" 
            case 563: this.name := "Flawed Topaz" 
            case 564: this.name := "Topaz" 
            case 565: this.name := "Flawless Topaz" 
            case 566: this.name := "Perfect Topaz" 
            case 567: this.name := "Chipped Sapphire" 
            case 568: this.name := "Flawed Sapphire" 
            case 569: this.name := "Sapphire" 
            case 570: this.name := "Flawless Sapphire" 
            case 571: this.name := "Perfect Sapphire" 
            case 572: this.name := "Chipped Emerald" 
            case 573: this.name := "Flawed Emerald" 
            case 574: this.name := "Emerald" 
            case 575: this.name := "Flawless Emerald" 
            case 576: this.name := "Perfect Emerald" 
            case 577: this.name := "Chipped Ruby" 
            case 578: this.name := "Flawed Ruby" 
            case 579: this.name := "Ruby" 
            case 580: this.name := "Flawless Ruby" 
            case 581: this.name := "Perfect Ruby" 
            case 582: this.name := "Chipped Diamond" 
            case 583: this.name := "Flawed Diamond" 
            case 584: this.name := "Diamond" 
            case 585: this.name := "Flawless Diamond" 
            case 586: this.name := "Perfect Diamond" 
            case 587: this.name := "Minor Healing Potion" 
            case 588: this.name := "Light Healing Potion" 
            case 589: this.name := "Healing Potion" 
            case 590: this.name := "Greater Healing Potion" 
            case 591: this.name := "Super Healing Potion" 
            case 592: this.name := "Minor Mana Potion" 
            case 593: this.name := "Light Mana Potion" 
            case 594: this.name := "Mana Potion" 
            case 595: this.name := "Greater Mana Potion" 
            case 596: this.name := "Super Mana Potion" 
            case 597: this.name := "Chipped Skull" 
            case 598: this.name := "Flawed Skull" 
            case 599: this.name := "Skull" 
            case 600: this.name := "Flawless Skull" 
            case 601: this.name := "Perfect Skull" 
            case 602: this.name := "Herb" 
            case 603: this.name := "Small Charm" 
            case 604: this.name := "Large Charm" 
            case 605: this.name := "Grand Charm" 
            case 606: this.name := "Small Red Potion" 
            case 607: this.name := "Large Red Potion" 
            case 608: this.name := "Small Blue Potion" 
            case 609: this.name := "Large Blue Potion" 
            case 610: this.name := "El Rune" 
            case 611: this.name := "Eld Rune" 
            case 612: this.name := "Tir Rune" 
            case 613: this.name := "Nef Rune" 
            case 614: this.name := "Eth Rune" 
            case 615: this.name := "Ith Rune" 
            case 616: this.name := "Tal Rune" 
            case 617: this.name := "Ral Rune" 
            case 618: this.name := "Ort Rune" 
            case 619: this.name := "Thul Rune" 
            case 620: this.name := "Amn Rune" 
            case 621: this.name := "Sol Rune" 
            case 622: this.name := "Shael Rune" 
            case 623: this.name := "Dol Rune" 
            case 624: this.name := "Hel Rune" 
            case 625: this.name := "Io Rune" 
            case 626: this.name := "Lum Rune" 
            case 627: this.name := "Ko Rune" 
            case 628: this.name := "Fal Rune" 
            case 629: this.name := "Lem Rune" 
            case 630: this.name := "Pul Rune" 
            case 631: this.name := "Um Rune" 
            case 632: this.name := "Mal Rune" 
            case 633: this.name := "Ist Rune" 
            case 634: this.name := "Gul Rune" 
            case 635: this.name := "Vex Rune" 
            case 636: this.name := "Ohm Rune" 
            case 637: this.name := "Lo Rune" 
            case 638: this.name := "Sur Rune" 
            case 639: this.name := "Ber Rune" 
            case 640: this.name := "Jah Rune" 
            case 641: this.name := "Cham Rune" 
            case 642: this.name := "Zod Rune" 
            case 643: this.name := "Jewel" 
            case 644: this.name := "Malah's Potion" 
            case 645: this.name := "Scroll of Knowledge" 
            case 646: this.name := "Scroll of Resistance" 
            case 647: this.name := "Key of Terror" 
            case 648: this.name := "Key of Hate" 
            case 649: this.name := "Key of Destruction" 
            case 650: this.name := "Diablo's Horn" 
            case 651: this.name := "Baal's Eye" 
            case 652: this.name := "Mephisto's Brain" 
            case 653: this.name := "Token of Absolution" 
            case 654: this.name := "Twisted Essence of Suffering" 
            case 655: this.name := "Charged Essense of Hatred" 
            case 656: this.name := "Burning Essence of Terror" 
            case 657: this.name := "Festering Essence of Destruction" 
            case 658: this.name := "Standard of Heroes"
            default: this.name := ""
        }
        
    }
}

